import { Inmueble } from './inmueble_resumen/inmueble.component.js';

export const INMUEBLES : Inmueble[] = [
	{
	  id_inmueble: 1,
	  descripcion: "Mi linda casita",
	  precio: 100000000,
	  direccion:"Polo Norte",
	  areaConstruccion:300,
	  areaTerreno:300,
	  numeroHabitaciones:2,
	  numeroBanyos:2,
	  numeroEstacionamientos:0,
	  tipoInmueble:"casa",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
	{
	  id_inmueble: 2,
	  descripcion: "Mi lindo apartamento",
	  precio: 50000000,
	  direccion:"Polo Norte",
	  areaConstruccion:300,
	  areaTerreno:300,
	  numeroHabitaciones:1,
	  numeroBanyos:1,
	  numeroEstacionamientos:1,
	  tipoInmueble:"apartamento",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
	{
	  id_inmueble: 3,
	  descripcion: "Mi lindo comercio",
	  precio: 150000000,
	  direccion:"Polo Norte",
	  areaConstruccion:300,
	  areaTerreno:300,
	  numeroHabitaciones:0,
	  numeroBanyos:2,
	  numeroEstacionamientos:2,
	  tipoInmueble:"comercio",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
	{
	  id_inmueble: 4,
	  descripcion: "Mi lindo rancho",
	  precio: 100000000,
	  direccion:"Polo Norte",
	  areaConstruccion:300,
	  areaTerreno:300,
	  numeroHabitaciones:2,
	  numeroBanyos:0,
	  numeroEstacionamientos:0,
	  tipoInmueble:"informal",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
	{
	  id_inmueble: 5,
	  descripcion: "Mi linda mansión",
	  precio: 50000000,
	  direccion:"Polo Norte",
	  areaConstruccion:3000,
	  areaTerreno:3000,
	  numeroHabitaciones:10,
	  numeroBanyos:10,
	  numeroEstacionamientos:1,
	  tipoInmueble:"mansión",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
	{
	  id_inmueble: 6,
	  descripcion: "Mi lindo terreno",
	  precio: 150000000,
	  direccion:"Polo Norte",
	  areaConstruccion:300,
	  areaTerreno:300,
	  numeroHabitaciones:0,
	  numeroBanyos:0,
	  numeroEstacionamientos:0,
	  tipoInmueble:"terreno",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
	{
	  id_inmueble: 7,
	  descripcion: "Mi lindo terreno",
	  precio: 150000000,
	  direccion:"Polo Norte",
	  areaConstruccion:300,
	  areaTerreno:300,
	  numeroHabitaciones:0,
	  numeroBanyos:0,
	  numeroEstacionamientos:0,
	  tipoInmueble:"terreno",
	  urlImagenPrincipal:"static/img/Two_Children_Teasing_a_Cat.png",
	  urlImagenesSecundarias:["static/img/Two_Children_Teasing_a_Cat.png"]
	},
];