# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasAdicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(blank=True, default='', max_length=40, verbose_name='Caracter\xedstica especial del inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Cercanias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cercania', models.CharField(blank=True, default='', max_length=40, verbose_name='Sitios notables cercanos al inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='', max_length=40, verbose_name='Detalles adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='FotosSecundariasURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotosSecundariaURL', models.TextField(verbose_name='Foto secundaria del inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InstalacionesComodidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion', models.CharField(blank=True, default='', max_length=40, verbose_name='Instalaciones adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDeInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Usar el formato <em>321.32</em>', max_digits=20, verbose_name='Precio del inmueble')),
                ('divisa', models.CharField(help_text='Usar el nombre de la divisa', max_length=20, verbose_name='Moneda en la que se oferta el inmueble')),
                ('descripcion', models.TextField(verbose_name='Breve descripci\xf3n')),
                ('tipoDeInmueble', models.CharField(choices=[('CA', 'Casa'), ('AP', 'Apartamento'), ('QU', 'Quinta'), ('TE', 'Terreno'), ('LO', 'Local'), ('CO', 'Comercio'), ('OF', 'Oficina'), ('IN', 'Informal')], default='CA', help_text='Usar una de las opciones', max_length=2, verbose_name='Tipo de Inmueble')),
                ('tipoDeOperacion', models.CharField(choices=[('VE', 'Venta'), ('AL', 'Alquiler')], default='VE', help_text='Usar una de las opciones', max_length=2, verbose_name='Tipo de Operaci\xf3n')),
                ('antiguedadDeInmueble', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', max_length=3, verbose_name='Cantidad de a\xf1os desde su construcci\xf3n')),
                ('numeroDeHabitaciones', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', max_length=3, verbose_name='Cantidad de habitaciones')),
                ('numeroDeBanyos', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', max_length=3, verbose_name='Cantidad de ba\xf1os')),
                ('nombreDelInmueble', models.CharField(help_text='Colocar el nombre del inmueble', max_length=40, verbose_name='Nombre del inmueble')),
                ('numeroDeEstacionamientos', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', max_length=3, verbose_name='N\xfamero de estacionamientos')),
                ('metrosDeConstruccion', models.PositiveIntegerField(help_text='Usar un entero positivo', max_length=10, verbose_name='Metros cuadrados de construcci\xf3n')),
                ('metrosDeTerreno', models.PositiveIntegerField(help_text='Usar un entero positivo', max_length=10, verbose_name='Metros cuadrados de terreno')),
                ('direccion', models.TextField(help_text='Colocar la direcci\xf3n del inmueble', verbose_name='Direcci\xf3n completa del inmueble')),
                ('fotoPrincipalURL', models.TextField(verbose_name='Foto principal del inmueble')),
                ('sePuedeMostrar', models.BooleanField(default=True, help_text='Usar un valor booleano', verbose_name='Si se puede mostrar a los visitantes')),
                ('fechaDeCreacion', models.DateField(auto_now_add=True)),
                ('fechaDeUltimaActualizacion', models.DateField(auto_now=True)),
                ('comprado', models.BooleanField(default=False, help_text='Usar un valor booleano', verbose_name='Si ya fue comprado')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos del usuario')),
                ('cedula', models.IntegerField(max_length=20, unique=True, verbose_name='C\xe9dula o identificaci\xf3n del usuario')),
                ('nacionalidad', models.CharField(max_length=20, verbose_name='Nacionalidad del usuario')),
                ('direccion', models.TextField(help_text='Colocar la direcci\xf3n completa del usuario.', unique=True, verbose_name='Direcci\xf3n completa del usuario')),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electr\xf3nico del usuario')),
            ],
        ),
        migrations.AddField(
            model_name='instalacionescomodidades',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='fotossecundariasurls',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='detalles',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='cercanias',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='caracteristicasadicionales',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
    ]
