# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaracteristicasAdicionales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracteristica', models.CharField(blank=True, default='', max_length=40, verbose_name='Caracter\xedstica especial del inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Cercanias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cercania', models.CharField(blank=True, default='', max_length=40, verbose_name='Sitios notables cercanos al inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='Detalles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(blank=True, default='', max_length=40, verbose_name='Detalles adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMoneda', models.CharField(help_text='Coloque el nombre de una divisa', max_length=20, verbose_name='Nombre de la moneda')),
                ('simbolo', models.CharField(blank=True, help_text='Coloque el s\xedmbolo de una divisa. Si es vac\xedo se usa el nombre.', max_length=20, null=True, verbose_name='S\xedmbolo de la moneda')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstado', models.CharField(help_text='Coloque el nombre de un estado', max_length=20, verbose_name='Nombre del estado')),
            ],
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Colocar el t\xedtulo de una foto', max_length=20, verbose_name='T\xedtulo de la foto')),
                ('fotoPrincipalURL', models.TextField(help_text='Direcci\xf3n de la foto en el servidor', verbose_name='Foto principal del inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='FotosSecundariasURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotosSecundariaURL', models.TextField(verbose_name='Foto secundaria del inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InstalacionesComodidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion', models.CharField(blank=True, default='', max_length=40, verbose_name='Instalaciones adicionales')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaDeInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Usar el formato <em>321.32</em>', max_digits=20, verbose_name='Precio del inmueble')),
                ('descripcion', models.TextField(verbose_name='Breve descripci\xf3n')),
                ('antiguedadDeInmueble', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', verbose_name='Cantidad de a\xf1os desde su construcci\xf3n')),
                ('numeroDeHabitaciones', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', verbose_name='Cantidad de habitaciones')),
                ('numeroDeBanyos', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', verbose_name='Cantidad de ba\xf1os')),
                ('nombreDelInmueble', models.CharField(help_text='Colocar el nombre del inmueble', max_length=40, verbose_name='Nombre del inmueble')),
                ('numeroDeEstacionamientos', models.PositiveSmallIntegerField(help_text='Usar un entero positivo', verbose_name='N\xfamero de estacionamientos')),
                ('metrosDeConstruccion', models.PositiveIntegerField(help_text='Usar un entero positivo', verbose_name='Metros cuadrados de construcci\xf3n')),
                ('metrosDeTerreno', models.PositiveIntegerField(help_text='Usar un entero positivo', verbose_name='Metros cuadrados de terreno')),
                ('direccion', models.TextField(help_text='Colocar la direcci\xf3n del inmueble', verbose_name='Direcci\xf3n completa del inmueble con pa\xeds, estado, municipio, parroquia y avenida.')),
                ('fotoPrincipalURL', models.TextField(verbose_name='Foto principal del inmueble')),
                ('sePuedeMostrar', models.BooleanField(default=True, help_text='Usar un valor booleano', verbose_name='Si se puede mostrar a los visitantes')),
                ('fechaDeCreacion', models.DateField(auto_now_add=True)),
                ('fechaDeUltimaActualizacion', models.DateField(auto_now=True)),
                ('comprado', models.BooleanField(default=False, help_text='Usar un valor booleano', verbose_name='Si ya fue comprado')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePais', models.CharField(help_text='Coloque el nombre de un pa\xeds', max_length=40, verbose_name='Nombre del pa\xeds')),
                ('nacionalidad', models.CharField(help_text='Coloque una nacionalidad', max_length=20, verbose_name='Nombre de la nacionalidad')),
                ('divisa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Divisa')),
            ],
        ),
        migrations.CreateModel(
            name='PrimeraDivisionAdministrativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDivision', models.CharField(help_text='Coloque el nombre de una divisi\xf3n administrativa siguiente a Estado o Provincia', max_length=20, verbose_name='Nombre de la divisi\xf3n administrativa (Ej: Municipio) siguiente a Estado o Provincia')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeInmueble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoDeInmueble', models.CharField(help_text='Coloque el nombre de un tipo de inmueble', max_length=20, verbose_name='Nombre del tipo de inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeOperacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDelTipoDeOperacion', models.CharField(help_text='Coloque el nombre de un tipo de operaci\xf3n', max_length=20, verbose_name='Nombre del tipo de operaci\xf3n')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=40, verbose_name='Nombres del usuario')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos del usuario')),
                ('cedula', models.IntegerField(unique=True, verbose_name='C\xe9dula o identificaci\xf3n del usuario')),
                ('direccion', models.TextField(help_text='Colocar la direcci\xf3n completa del usuario.', verbose_name='Direcci\xf3n completa del usuario')),
                ('telefono', models.CharField(max_length=15, unique=True)),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo electr\xf3nico del usuario')),
                ('foto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Foto')),
                ('nacionalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Pais')),
            ],
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmueblesComprados', to='vinmuebles.Usuario', verbose_name='Nuevo due\xf1o del inmueble'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='divisa',
            field=models.ForeignKey(help_text='Usar el nombre de la divisa', on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Divisa', verbose_name='Moneda en la que se oferta el inmueble'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='duenyo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmueblesPropiosVendidosOenVenta', to='vinmuebles.Usuario', verbose_name='Due\xf1o del inmueble'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Estado'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.PrimeraDivisionAdministrativa'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Pais'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='tipoDeInmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.TipoDeInmueble'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='tipoDeOperacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.TipoDeOperacion'),
        ),
        migrations.AddField(
            model_name='ofertadeinmueble',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmueblesVendidosOenVenta', to='vinmuebles.Usuario', verbose_name='Vendedor del inmueble'),
        ),
        migrations.AddField(
            model_name='instalacionescomodidades',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='fotossecundariasurls',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.Pais'),
        ),
        migrations.AddField(
            model_name='detalles',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='cercanias',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
        migrations.AddField(
            model_name='caracteristicasadicionales',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinmuebles.OfertaDeInmueble'),
        ),
    ]
